schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "parrot_lipsync"
version = "1.1.1"
name = "Parrot Lipsync"
tagline = "Auto generate keyframes for lipsyncing audio"
maintainer = "Mark McKay"
#maintainer = "Developer name <email@address.com>"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional link to documentation, support, source files, etc
# website = "https://extensions.blender.org/add-ons/my-example-package/"
website = "https://github.com/blackears/parrotLipsync"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Animation", "Sequencer"]

blender_version_min = "4.2.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
#license = [
#  "SPDX:GPL-3.0-or-later",
#]
license = [
  "SPDX:MIT",
]
# Optional: required by some licenses.
# copyright = [
#   "2002-2024 Developer Name",
#   "1998 Company Name",
# ]

# Optional list of supported platforms. If omitted, the extension will be available in all operating systems.
# platforms = ["windows-x64", "macos-arm64", "linux-x64"]
# Other supported platforms: "windows-arm64", "macos-x64"
platforms = ["windows-x64", "macos-x64", "linux-x64"]

# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
# wheels = [
#   "./wheels/hexdump-3.3-py3-none-any.whl",
#   "./wheels/jsmin-3.0.1-py3-none-any.whl",
# ]


wheels = [
    "./wheels/allosaurus-1.0.2-py3-none-any.whl",
    "./wheels/editdistance-0.8.1-cp310-cp310-macosx_10_9_x86_64.whl",
    "./wheels/editdistance-0.8.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/editdistance-0.8.1-cp311-cp311-win_amd64.whl",
    "./wheels/filelock-3.16.0-py3-none-any.whl",
    "./wheels/fsspec-2024.9.0-py3-none-any.whl",
    "./wheels/jinja2-3.1.4-py3-none-any.whl",
    "./wheels/llvmlite-0.43.0-cp310-cp310-macosx_10_9_x86_64.whl",
    "./wheels/llvmlite-0.43.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/llvmlite-0.43.0-cp311-cp311-win_amd64.whl",
    "./wheels/MarkupSafe-2.1.5-cp310-cp310-macosx_10_9_x86_64.whl",
    "./wheels/MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/MarkupSafe-2.1.5-cp311-cp311-win_amd64.whl",
    "./wheels/mpmath-1.3.0-py3-none-any.whl",
    "./wheels/munkres-1.1.4-py2.py3-none-any.whl",
    "./wheels/networkx-3.3-py3-none-any.whl",
    "./wheels/numba-0.60.0-cp310-cp310-macosx_10_9_x86_64.whl",
    "./wheels/numba-0.60.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
    "./wheels/numba-0.60.0-cp311-cp311-win_amd64.whl",
    "./wheels/numpy-2.0.2-cp310-cp310-macosx_10_9_x86_64.whl",
    "./wheels/numpy-2.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/numpy-2.0.2-cp311-cp311-win_amd64.whl",
    "./wheels/nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl",
    "./wheels/nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl",
    "./wheels/nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl",
    "./wheels/nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl",
    "./wheels/nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl",
    "./wheels/nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl",
    "./wheels/nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl",
    "./wheels/nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl",
    "./wheels/nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl",
    "./wheels/nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl",
    "./wheels/nvidia_nvjitlink_cu12-12.6.68-py3-none-manylinux2014_x86_64.whl",
    "./wheels/nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl",
    "./wheels/panphon-0.21.2-py2.py3-none-any.whl",
    "./wheels/pip-24.2-py3-none-any.whl",
    "./wheels/PyYAML-6.0.2-cp310-cp310-macosx_10_9_x86_64.whl",
    "./wheels/PyYAML-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/PyYAML-6.0.2-cp311-cp311-win_amd64.whl",
    "./wheels/regex-2024.9.11-cp310-cp310-macosx_10_9_x86_64.whl",
    "./wheels/regex-2024.9.11-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/regex-2024.9.11-cp311-cp311-win_amd64.whl",
    "./wheels/resampy-0.4.3-py3-none-any.whl",
    "./wheels/scipy-1.14.1-cp310-cp310-macosx_10_13_x86_64.whl",
    "./wheels/scipy-1.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/scipy-1.14.1-cp311-cp311-win_amd64.whl",
    "./wheels/setuptools-74.1.2-py3-none-any.whl",
    "./wheels/setuptools-75.1.0-py3-none-any.whl",
    "./wheels/sympy-1.13.2-py3-none-any.whl",
    "./wheels/torch-2.2.2-cp310-none-macosx_10_9_x86_64.whl",
    "./wheels/torch-2.4.1-cp310-cp310-manylinux1_x86_64.whl",
    "./wheels/torch-2.4.1-cp311-cp311-win_amd64.whl",
    "./wheels/triton-3.0.0-1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
    "./wheels/typing_extensions-4.12.2-py3-none-any.whl",
    "./wheels/unicodecsv-0.14.1-py3-none-any.whl",
    "./wheels/wheel-0.44.0-py3-none-any.whl",
]


# # Optional: add-ons can list which resources they will require:
# # * files (for access of any filesystem operations)
# # * network (for internet access)
# # * clipboard (to read and/or write the system clipboard)
# # * camera (to capture photos and videos)
# # * microphone (to capture audio)
# #
# # If using network, remember to also check `bpy.app.online_access`
# # https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
# #
# # For each permission it is important to also specify the reason why it is required.
# # Keep this a single short sentence without a period (.) at the end.
# # For longer explanations use the documentation or detail page.
#
# [permissions]
# network = "Need to sync motion-capture data to server"
# files = "Import/export FBX from/to disk"
# clipboard = "Copy and paste bone transforms"

# Optional: build settings.
# https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]
